const TESTCASE_TIMEOUT = 60000;
const FINDING_ELEMENT_TIMEOUT = 10000;

const CATEGORIES = {
  ACCESSORIES: "ACCESSORIES",
  BOTTOMS: "BOTTOMS",
  JACKETS: "JACKETS",
  SHOES: "SHOES",
  TOPS: "TOPS",
  VESTS: "VESTS",
};

const COLORS = {
  BLUE: "BLUE",
  BLACK: "BLACK",
  GREY: "GREY",
  BROWN: "BROWN",
  GREEN: "GREEN",
  VIOLET: "VIOLET",
  RED: "RED",
  ORANGE: "ORANGE",
  WHITE: "WHITE",
  PINK: "PINK",
  YELLOW: "YELLOW",
  PATTERN: "PATTERN",
};

const SIZES = {
  XS: "XS",
  S: "S",
  M: "M",
  L: "L",
  XL: "XL",
  XXL: "XXL",
};

module.exports = {
  TESTCASE_TIMEOUT,
  FINDING_ELEMENT_TIMEOUT,
  CATEGORIES,
  COLORS,
  SIZES,
};
